# Generated by Django 5.2.4 on 2025-07-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_remove_tweet_user_tweet_content2_alter_tweet_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='content2',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='content',
            new_name='name',
        ),
    ]
